### ISSUE TITLE
Permission Denied when running OCR on documents

### ISSUE THREAD

**Issue by jangelfdez** [microsoft/OCR-Form-Tools#379]
**Describe the bug**
After following the *Deploy with Azure Container Instances (ACI)* tutorial, it is not possible to continue with the next steps due a "Permission Denied" error.

**To Reproduce**
1. Follow the tutorial (https://docs.microsoft.com/en-us/azure/cognitive-services/form-recognizer/deploy-label-tool#deploy-with-azure-container-instances-aci)
2. Open Tag Editor
3. Select first document, the "Running OCR" message would appear and it would fail

**Expected behavior**
I expect to continue with the tutorial tagging my documents

**Screenshots**
![image](https://user-images.githubusercontent.com/992009/86533661-ef92b400-bed2-11ea-9f6e-44ec262c50bd.png)

**Desktop (please complete the following information):**
 - App Service

**Comment by xinase** [comment]
First, please make sure you have the correct endpoint and key, also the SAS token to your Azure Blob Storage folder.

Sent from my iPhone

On Jul 5, 2020, at 6:20 AM, José Ángel Fernández <notifications@github.com> wrote:

﻿

Describe the bug
After following the Deploy with Azure Container Instances (ACI) tutorial, it is not possible to continue with the next steps due a "Permission Denied" error.

To Reproduce
Steps to reproduce the behavior:

  1.  Follow the tutorial (https://docs.microsoft.com/en-us/azure/cognitive-services/form-recognizer/deploy-label-tool#deploy-with-azure-container-instances-aci<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fcognitive-services%2Fform-recognizer%2Fdeploy-label-tool%23deploy-with-azure-container-instances-aci&data=02%7C01%7C%7C08e523aa47b04336533708d820e63ab5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637295520477458082&sdata=uMRMs%2B8jVVWOAG1YbzGcC72XJG%2BOSLVU%2Fqq5Xnh4vD8%3D&reserved=0>)
  2.  Open Tag Editor
  3.  Select first document, the "Running OCR" message would appear and it would fail

Expected behavior
I expect to continue with the tutorial tagging my documents

Screenshots
[image]<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F992009%2F86533661-ef92b400-bed2-11ea-9f6e-44ec262c50bd.png&data=02%7C01%7C%7C08e523aa47b04336533708d820e63ab5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637295520477458082&sdata=nLiARlLWXqA8dR11dAbKykhD3nKzJ5eeYbIAvskQKKg%3D&reserved=0>

Desktop (please complete the following information):

  *   App Service

**Comment by jangelfdez** [comment]
Using the same credentials it works on https://fott.azurewebsites.net/ but not on my local deployment. Something that I could be missing?

**Comment by stew-ro** [comment]
@jangelfdez Can you check your network log for https://{endpoint}/formrecognizer/v2.0-preview/layout/analyze to make sure the request header "Ocp-Apim-Subscription-Key" is correct?

Also, can share the request and response headers for that log which aren't protected info (e.g. don't share "Ocp-Apim-Subscription-Key")?

**Comment by jangelfdez** [comment]
Hi Stew!

I was checking again the issue and at this time is working without any issue with the same information. Maybe a transitory issue. I would pay attention in case it is reproduced again.
