### ISSUE TITLE
400 (Bad Request) error when uploading PDF files

### ISSUE THREAD

**Issue by iMicknl** [microsoft/OCR-Form-Tools#888]
**Describe the bug**
For some PDF files, you will retrieve the error "Cannot connect to form recognizer backend URL. Please make sure the network connection is good and specified endpoint is correct.", but this is not related to a network error, but to a service error.

Looking at the network requests, there is no response, just a 400 (Bad Request) header. This happens to me more often with other PDF files, where it works if I convert the PDF file to PNG.

**To Reproduce**
1. Download the prebuilt receipts from https://azure.microsoft.com/en-us/services/cognitive-services/form-recognizer/.
2. Go to https://fott-preview.azurewebsites.net/prebuilts-analyze
3. Choose local file, choose one of the prebuilt receipts PDF.

**Expected behavior**
A clear error message / the service backend fixed.

**Screenshots**
![image](https://user-images.githubusercontent.com/1424596/110455453-bbf2d400-80c8-11eb-82fb-94b428cc6555.png)

![image](https://user-images.githubusercontent.com/1424596/110455390-ad0c2180-80c8-11eb-9565-abaeebf25e9b.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Docker version: https://fott-preview.azurewebsites.net/prebuilts-analyze
 - Browser: Edge Chromium
 - Version: latest

**Comment by buddhawang** [comment]
Thanks, @iMicknl! 
It turns out to be the PDF dimension exceeds the supported range from service side. I will follow up to see if we can resize the sample files on https://azure.microsoft.com/en-us/services/cognitive-services/form-recognizer/.
We had an update on the FOTT side for showing error message from service side (ref: #894), the change is rolled out to https://fott-preview-private.azurewebsites.net/prebuilts-analyze and will go out to https://fott-preview.azurewebsites.net/prebuilts-analyze this week.

**Comment by iMicknl** [comment]
Thanks, @buddhawang! I can confirm that this has been fixed.

![image](https://user-images.githubusercontent.com/1424596/111150463-69189100-858e-11eb-9596-6dc42c2e6d1c.png)

This new message is very helpful, and indeed it would be good if the sample images on Azure.com could have the right size as well.
